paths:
  dataset_dir: ${REPO_ROOT}/MD/dataset
  training_dir: ${REPO_ROOT}/MD/training
  run_fdf_name: RUN.fdf
  run_out_name: RUN.out
  training_config_name: config.yaml
  venv_activate: /home/christian/graph2mat-env/bin/activate
commands:
  graph2mat: graph2mat
  siesta: siesta
  shell: bash
md:
  type_of_run: verlet
  steps: 10
  basis_size: DZP
  basis_type: split
  energy_shift: 0.03 eV
  mesh_cutoff: 200 Ry
  xc_functional: GGA
  xc_authors: PBE
  max_scf_iterations: 200
  solution_method: diagon
  dm_mixing_weight: 0.02
  dm_number_pulay: 3
  dm_tolerance: 1.d-5
  dm_require_energy_convergence: T
  dm_energy_tolerance: 1.e-5 eV
  spin_polarized: F
  fix_spin: F
  non_collinear_spin: F
  save_hs_file: true
  save_hs: true
  save_de: true
  lua_script: md_store.lua
  force_aux_cell: true
  lattice_constant:
    value: 1.0
    unit: Ang
  lattice_vectors:
  - - 15.0
    - 0.0
    - 0.0
  - - 0.0
    - 15.0
    - 0.0
  - - 0.0
    - 0.0
    - 15.0
  species:
  - index: 1
    atomic_number: 8
    symbol: O
  - index: 2
    atomic_number: 1
    symbol: H
  coordinates_format: Ang
  atoms:
  - label: O
    species_index: 1
    position:
    - 5.0
    - 5.0
    - 0.119262
  - label: H
    species_index: 2
    position:
    - 5.0
    - 5.763239
    - -0.477047
  - label: H
    species_index: 2
    position:
    - 5.0
    - 4.336839
    - -0.477047
training:
  data:
    out_matrix: hamiltonian
    symmetric_matrix: true
    sub_point_matrix: false
    n_matrix_components: 2
    basis_files: ../dataset/MD_steps/basis/*.ion.xml
    train_runs: ../dataset/splits/train/*/RUN.fdf
    batch_size: 10
    store_in_memory: true
  model:
    num_interactions: 1
    correlation: 1
    max_ell: 2
    hidden_irreps: 10x0e + 10x1o + 10x2e
    loss: graph2mat.metrics.block_type_mae
    optim_lr: 0.005
  trainer:
    accelerator: cpu
    logger:
      class_path: TensorBoardLogger
      init_args:
        name: my_first_model
        save_dir: lightning_logs
    max_epochs: 200
checkpoint:
  path: null
  auto_best: true
  search_glob: lightning_logs/**/checkpoints/best-*.ckpt
  selection: latest_version
testing:
  test_runs: ../dataset/splits/test/*/RUN.fdf
  callbacks:
    plot_matrix_error: false
    show_plot: false
    samplewise_metrics_logger: false
prediction:
  predict_structs: ../dataset/splits/test/*/RUN.fdf
  output_file: ML_prediction.HSX
  callbacks:
    matrix_writer: true
pipeline:
  steps:
  - generate_md_dataset
  - run_md_training
  - run_md_testing
  - run_md_prediction
splits:
  enabled: true
  strategy: spread
  train: 8
  validation: 1
  test: 1
