#!/usr/bin/env python3
"""Write matched Graph2Mat configs for MD and SIESTA-FC datasets."""

from __future__ import annotations

import argparse
import copy
from pathlib import Path
from typing import Any

import yaml


REPO_ROOT = Path(__file__).resolve().parents[2]
MD_CONFIG = REPO_ROOT / "MD" / "pipeline_config.yaml"
FC_CONFIG = REPO_ROOT / "AtomDisplacement" / "pipeline_config.yaml"


def load_yaml(path: Path) -> dict[str, Any]:
    if not path.exists():
        raise RuntimeError(f"No existe el archivo requerido: {path}")
    with path.open("r", encoding="utf-8") as handle:
        data = yaml.safe_load(handle)
    if not isinstance(data, dict):
        raise RuntimeError(f"El YAML debe contener un diccionario: {path}")
    return data


def graph2mat_training_block(config: dict[str, Any], dataset_kind: str) -> dict[str, Any]:
    if dataset_kind == "md":
        block = copy.deepcopy(config["training"])
        block["trainer"]["logger"]["init_args"]["name"] = "h2o_md_model"
        return block

    block = {
        "data": copy.deepcopy(config["training"]["data"]),
        "model": copy.deepcopy(config["training"]["model"]),
        "trainer": copy.deepcopy(config["training"]["trainer"]),
    }
    block["trainer"]["logger"]["init_args"]["name"] = "h2o_fc_model"
    return block


def set_portable_paths(block: dict[str, Any], dataset_kind: str) -> None:
    data = block["data"]
    if dataset_kind == "md":
        data["basis_files"] = "../MD/dataset/MD_steps/basis/*.ion.xml"
        data["train_runs"] = "../MD/dataset/MD_steps/*/RUN.fdf"
    else:
        data["basis_files"] = "../AtomDisplacement/dataset/FC_steps/basis/*.ion.xml"
        data["train_runs"] = "../AtomDisplacement/dataset/FC_steps/*/RUN.fdf"
        data.pop("runs_json", None)


def force_shared_hyperparams(md_block: dict[str, Any], fc_block: dict[str, Any]) -> None:
    """Keep the two configs identical except for dataset paths and logger name."""
    fc_data = fc_block["data"]
    fc_logger = fc_block["trainer"]["logger"]["init_args"]["name"]

    fc_block["model"] = copy.deepcopy(md_block["model"])
    fc_block["trainer"] = copy.deepcopy(md_block["trainer"])
    fc_block["trainer"]["logger"]["init_args"]["name"] = fc_logger

    for key in ("out_matrix", "symmetric_matrix", "batch_size", "store_in_memory"):
        if key in md_block["data"]:
            fc_data[key] = copy.deepcopy(md_block["data"][key])
    fc_block["data"] = fc_data
    set_portable_paths(md_block, "md")
    set_portable_paths(fc_block, "fc")


def validate_config(block: dict[str, Any], label: str) -> None:
    data = block.get("data", {})
    required = ("out_matrix", "symmetric_matrix", "basis_files")
    missing = [key for key in required if key not in data]
    if missing:
        raise RuntimeError(f"{label}: faltan claves data requeridas: {missing}")
    if data["out_matrix"] != "hamiltonian":
        raise RuntimeError(f"{label}: data.out_matrix debe ser 'hamiltonian'")
    if not bool(data["symmetric_matrix"]):
        raise RuntimeError(f"{label}: data.symmetric_matrix debe ser True")


def write_config(path: Path, block: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        "# Generated by Comparison/scripts/write_graph2mat_configs.py\n"
        + yaml.safe_dump(block, sort_keys=False, default_flow_style=False, allow_unicode=False),
        encoding="utf-8",
    )


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Create matched config_md.yaml and config_fc.yaml for Graph2Mat."
    )
    parser.add_argument("--md-config", type=Path, default=MD_CONFIG)
    parser.add_argument("--fc-config", type=Path, default=FC_CONFIG)
    parser.add_argument("--output-dir", type=Path, default=REPO_ROOT / "configs")
    parser.add_argument("--dry-run", action="store_true")
    return parser


def main() -> int:
    args = build_parser().parse_args()
    md_pipeline = load_yaml(args.md_config)
    fc_pipeline = load_yaml(args.fc_config)

    md_block = graph2mat_training_block(md_pipeline, "md")
    fc_block = graph2mat_training_block(fc_pipeline, "fc")
    force_shared_hyperparams(md_block, fc_block)
    validate_config(md_block, "config_md")
    validate_config(fc_block, "config_fc")

    outputs = {
        "config_md.yaml": md_block,
        "config_fc.yaml": fc_block,
    }
    for name, block in outputs.items():
        path = args.output_dir / name
        if args.dry_run:
            print(f"[DRY-RUN] Escribir {path}")
        else:
            write_config(path, block)
            print(f"[OK] Escrito {path}")

    print("\nComandos:")
    print(f"  cd {args.output_dir} && graph2mat models mace main fit -c config_md.yaml")
    print(f"  cd {args.output_dir} && graph2mat models mace main fit -c config_fc.yaml")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
