#!/usr/bin/env python3
"""Generate a reduced graphene 5x2 reuse payload for 600-epoch configs only.

This payload:
- reuses the datasets already generated by the completed 20-100 4-seed sweep;
- resumes from that sweep so completed matching runs are not retrained;
- keeps only the 600-epoch anchor configs for Graph2Mat and DeepH;
- keeps only training seeds 1 and 2.
"""

from __future__ import annotations

import copy
import json
import time
from pathlib import Path
from typing import Any


REPO_ROOT = Path(__file__).resolve().parents[2]
CONFIG_DIR = REPO_ROOT / "Comparison" / "config"

BASE_PAYLOAD = CONFIG_DIR / "graphene_5x2_snapshot_scaling_20_100_4seeds_payload.json"
SOURCE_RUN_ROOT = (
    REPO_ROOT
    / "Comparison"
    / "results"
    / "graphene_5x2_snapshot_scaling_20_100_4seeds"
    / "graphene_5x2_snapshot_scaling_20_100_4seeds_20260616_121916"
)

RUN_TAG = "graphene_5x2_snapshot_scaling_reuse_600epochs_2seeds"
OUT_PAYLOAD = CONFIG_DIR / f"{RUN_TAG}_payload.json"
TRAINING_SEEDS = {1, 2}


def load_json(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def run_seed(run: dict[str, Any]) -> int | None:
    overrides = run.get("overrides") or {}
    raw = overrides.get("seed_everything", overrides.get("seed"))
    if raw in (None, ""):
        return None
    return int(raw)


def run_epochs(run: dict[str, Any]) -> int | None:
    overrides = run.get("overrides") or {}
    raw = overrides.get("max_epochs", overrides.get("epochs"))
    if raw in (None, ""):
        return None
    return int(raw)


def selected_manual_runs(base_payload: dict[str, Any]) -> list[dict[str, Any]]:
    selected: list[dict[str, Any]] = []
    for template in base_payload.get("training_sweep", {}).get("manual_runs") or []:
        seed = run_seed(template)
        epochs = run_epochs(template)
        if seed not in TRAINING_SEEDS:
            continue
        if epochs != 600:
            continue
        selected.append(copy.deepcopy(template))
    if not selected:
        raise RuntimeError("No 600-epoch / 2-seed manual runs were selected from the base payload.")
    ids = [str(item.get("config_id") or "") for item in selected]
    if len(ids) != len(set(ids)):
        raise RuntimeError("Duplicate config_id values detected in the reduced payload.")
    return selected


def main() -> None:
    if not SOURCE_RUN_ROOT.exists():
        raise RuntimeError(f"Source run root does not exist: {SOURCE_RUN_ROOT}")
    if not (SOURCE_RUN_ROOT / "summary" / "dataset_sweep_summary.json").exists():
        raise RuntimeError(
            "Source run root is missing summary/dataset_sweep_summary.json: "
            f"{SOURCE_RUN_ROOT}"
        )
    if not (SOURCE_RUN_ROOT / "sweep" / "training_sweep_manifest.json").exists():
        raise RuntimeError(
            "Source run root is missing sweep/training_sweep_manifest.json: "
            f"{SOURCE_RUN_ROOT}"
        )

    base_payload = load_json(BASE_PAYLOAD)
    manual_runs = selected_manual_runs(base_payload)
    stamp = time.strftime("%Y%m%d_%H%M%S")
    run_id = f"{RUN_TAG}_{stamp}"

    payload = copy.deepcopy(base_payload)
    payload["description"] = (
        "Graphene 5x2 train-only reuse payload. It reuses the validated 20-100 snapshot "
        "datasets from the completed 4-seed sweep, resumes matching completed runs from that "
        "sweep, and keeps only the 600-epoch Graph2Mat/DeepH anchor configs with seeds 1 and 2."
    )
    payload["source_reference_payloads"] = [str(BASE_PAYLOAD.relative_to(REPO_ROOT))]
    payload["source_reference_runs"] = [SOURCE_RUN_ROOT.name]
    payload["dataset_mode"] = "full_strict_pipeline"
    payload["run_mode"] = "full_strict_pipeline"
    payload["reuse_dataset_sweep_from_run_root"] = str(SOURCE_RUN_ROOT)
    payload["resume_training_sweep_from_run_root"] = str(SOURCE_RUN_ROOT)
    payload["dataset_root"] = f"${{REPO_ROOT}}/Comparison/datasets/{RUN_TAG}"
    payload["output_root"] = f"${{REPO_ROOT}}/Comparison/results/{RUN_TAG}"
    payload["run_id"] = run_id
    payload["dataset_sweep"] = {
        "enabled": True,
        "max_datasets": 5,
        "recipes": list((base_payload.get("dataset_sweep") or {}).get("recipes") or []),
        "reuse_only": True,
        "notes": (
            "Actual dataset paths are reused from the prior graphene_5x2 20-100 sweep via "
            "reuse_dataset_sweep_from_run_root. No MD/SIESTA dataset generation is launched."
        ),
    }
    payload["training_sweep"]["manual_runs"] = manual_runs
    payload["training_sweep"]["max_runs"] = len(manual_runs)
    payload["training_sweep"]["apply_to_datasets"] = ["all"]
    payload.setdefault("notes", {})
    payload["notes"].update(
        {
            "intended_use": "Reuse + resume reduced snapshot-scaling sweep for 600-epoch configs only.",
            "dataset_generation": "disabled",
            "reuse_mode": "reuse_dataset_sweep_from_run_root + resume_training_sweep_from_run_root",
            "source_run_root": str(SOURCE_RUN_ROOT),
            "training_seeds": sorted(TRAINING_SEEDS),
            "configs_per_dataset": 2,
            "expected_dataset_sizes": [20, 40, 60, 80, 100],
            "expected_training_runs": len(manual_runs),
            "force_constants_used": False,
        }
    )

    OUT_PAYLOAD.write_text(
        json.dumps(payload, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )
    print(f"Wrote payload: {OUT_PAYLOAD}")
    print(f"run_id: {run_id}")
    print(f"training runs: {len(manual_runs)}")


if __name__ == "__main__":
    main()
