_instantiator: pytorch_lightning.cli.instantiate_module
avg_num_neighbors: 1.0
basis_files: ../dataset/MD_steps/basis/*.ion.xml
basis_grouping: point_type
basis_table: "Unable to serialize instance \t- Type: 1. Basis: ((2, 0, 1), (1, 1,\
  \ -1)). MaxR: 2.720.\n\t- Type: 8. Basis: ((2, 0, 1), (2, 1, -1), (1, 2, 1)). MaxR:\
  \ 2.214."
batch_size: 10
copy_root_to_tmp: false
correlation: 1
edge_block_readout: graph2mat.bindings.e3nn.E3nnSimpleEdgeBlock
edge_hidden_irreps: 4x0e+4x1o+4x2e
hidden_irreps: 10x0e + 10x1o + 10x2e
initial_node_feats: OneHotZ
interaction_cls: mace.modules.RealAgnosticResidualInteractionBlock
interaction_cls_first: mace.modules.RealAgnosticResidualInteractionBlock
loader_threads: 1
loss: graph2mat.core.data.metrics.block_type_mae
max_ell: 2
n_matrix_components: 2
no_basis: null
node_block_readout: graph2mat.bindings.e3nn.E3nnSimpleNodeBlock
num_bessel: 10
num_interactions: 1
num_polynomial_cutoff: 3
optim_amsgrad: true
optim_lr: 0.005
optim_wdecay: 5.0e-07
out_matrix: hamiltonian
predict_structs: null
preprocessing_edges: graph2mat.bindings.e3nn.E3nnEdgeMessageBlock
preprocessing_edges_reuse_nodes: false
preprocessing_nodes: null
readout_per_interaction: false
root_dir: .
rotating_pool_size: null
runs_json: null
store_in_memory: true
sub_point_matrix: true
symmetric_matrix: true
test_runs: ../dataset/MD_steps/25/RUN.fdf
train_runs: ../dataset/MD_steps/*/RUN.fdf
val_runs: null
version: new
